recorder:
  include:
    entities:
      - sensor.cargador_aragon
      - sensor.cargador_conquistador
      - sensor.cargador_palmanyola_dalias
      - sensor.cargador_palmanyola_violetes
      - sensor.cargador_sant_miquel
      - sensor.cargador_paseo_mallorca
      - sensor.cargador_sestanyol

rest:
  resource: https://api.efimob.net/users/api/providers/efimob/organizations/melib/chargepoints?bounding-box-sw-lat=30.378878895325336&bounding-box-sw-long=-5.802556201815605&bounding-box-ne-lat=47.69966010198559&bounding-box-ne-long=11.07244547456503
  scan_interval: 120
  headers:
    User-Agent: MelibApp/3.0.3+android
    Accept-Encoding: gzip
  sensor:
    - name: Cargador Conquistador
      # melibmallo101
#      json_attributes_path: "$.[?(@.location.id=='2d3b0520-fb79-11ec-8015-2bcdc27f95cc')].location"
      json_attributes_path: "$[*].chargepoints[?(@.serialOCPP=='melibmallo101')]"
      json_attributes:
        - name
        - status
        - connected
        - numberPhases
      value_template: >-
          {% set chargepointsList = namespace(chargepoints=[]) %}
          {% for cargador in value_json %}
          {% set chargepointsList.chargepoints = chargepointsList.chargepoints + cargador.chargepoints %}
          {%- endfor %}
          {% set status = (chargepointsList.chargepoints | selectattr('serialOCPP','eq','melibmallo101') | list | first).status %}
          {%- if status == 'Busy' %}
            Ocupado
          {% elif status == 'Available' %}
            Libre
          {% elif status == 'OutOfOrder' %}
            Fuera de servicio
          {% else %}
            Desconocido
          {%- endif %}

    - name: Cargador Aragón
      # melibmallo99
#      json_attributes_path: "$.[?(@.location.id=='277289d0-fb86-11ec-8015-2bcdc27f95cc')].location"
      json_attributes_path: "$[*].chargepoints[?(@.serialOCPP=='melibmallo99')]"
      json_attributes:
        - name
        - status
        - connected
        - numberPhases
      value_template: >-
          {% set chargepointsList = namespace(chargepoints=[]) %}
          {% for cargador in value_json %}
          {% set chargepointsList.chargepoints = chargepointsList.chargepoints + cargador.chargepoints %}
          {%- endfor %}
          {% set status = (chargepointsList.chargepoints | selectattr('serialOCPP','eq','melibmallo99') | list | first).status %}
          {%- if status == 'Busy' %}
            Ocupado
          {% elif status == 'Available' %}
            Libre
          {% elif status == 'OutOfOrder' %}
            Fuera de servicio
          {% else %}
            Desconocido
          {%- endif %}

    - name: Cargador Sant Miquel
      # melibmallo97
#      json_attributes_path: "$.[?(@.location.id=='9853e690-fc3e-11ec-8015-2bcdc27f95cc')].location"
      json_attributes_path: "$[*].chargepoints[?(@.serialOCPP=='melibmallo97')]"
      json_attributes:
        - name
        - status
        - connected
        - numberPhases
      value_template: >-
          {% set chargepointsList = namespace(chargepoints=[]) %}
          {% for cargador in value_json %}
          {% set chargepointsList.chargepoints = chargepointsList.chargepoints + cargador.chargepoints %}
          {%- endfor %}
          {% set status = (chargepointsList.chargepoints | selectattr('serialOCPP','eq','melibmallo97') | list | first).status %}
          {%- if status == 'Busy' %}
            Ocupado
          {% elif status == 'Available' %}
            Libre
          {% elif status == 'OutOfOrder' %}
            Fuera de servicio
          {% else %}
            Desconocido
          {%- endif %}

    - name: Cargador Palmanyola Dalias
      # coming soon
      json_attributes_path: "$.[?(@.location.id=='85ae19c0-05c1-11ed-aa43-f58cc380021c')].location"
#      json_attributes_path: "$[*].chargepoints[?(@.serialOCPP=='melibmalloxx')]"
      json_attributes:
        - id
        - name
        - status
      value_template: >-
          {% set status = (value_json | selectattr('location.id','eq','85ae19c0-05c1-11ed-aa43-f58cc380021c') | list | first).location.status %}
          {%- if status == 'Busy' %}
            Ocupado
          {% elif status == 'Available' %}
            Libre
          {% elif status == 'OpeningSoon' %}
            Próximamente
          {% else %}
            Desconocido
          {%- endif %}

    - name: Cargador Palmanyola Violetes
      # coming soon
      json_attributes_path: "$.[?(@.location.id=='f66750f0-034b-11ed-aa43-f58cc380021c')].location"
#      json_attributes_path: "$[*].chargepoints[?(@.serialOCPP=='melibmalloyy')]"
      json_attributes:
        - id
        - name
        - status
      value_template: >-
          {% set status = (value_json | selectattr('location.id','eq','f66750f0-034b-11ed-aa43-f58cc380021c') | list | first).location.status %}
          {%- if status == 'Busy' %}
            Ocupado
          {% elif status == 'Available' %}
            Libre
          {% elif status == 'OpeningSoon' %}
            Próximamente
          {% else %}
            Desconocido
          {%- endif %}

    - name: Cargador Paseo Mallorca
      # melibmallo96
#      json_attributes_path: "$.[?(@.location.id=='fc2e9b90-fb6e-11ec-8015-2bcdc27f95cc')].location"
      json_attributes_path: "$[*].chargepoints[?(@.serialOCPP=='melibmallo96')]"
      json_attributes:
        - name
        - status
        - connected
        - numberPhases
      value_template: >-
          {% set chargepointsList = namespace(chargepoints=[]) %}
          {% for cargador in value_json %}
          {% set chargepointsList.chargepoints = chargepointsList.chargepoints + cargador.chargepoints %}
          {%- endfor %}
          {% set status = (chargepointsList.chargepoints | selectattr('serialOCPP','eq','melibmallo96') | list | first).status %}
          {%- if status == 'Busy' %}
            Ocupado
          {% elif status == 'Available' %}
            Libre
          {% elif status == 'OutOfOrder' %}
            Fuera de servicio
          {% else %}
            Desconocido
          {%- endif %}

    - name: Cargador Sestanyol
      # melibmallo59
#      json_attributes_path: "$.[?(@.location.id=='e65fdb00-f2ca-11ec-8015-2bcdc27f95cc')].location"
      json_attributes_path: "$[*].chargepoints[?(@.serialOCPP=='melibmallo59')]"
      json_attributes:
        - name
        - status
        - connected
        - numberPhases
      value_template: >-
          {% set chargepointsList = namespace(chargepoints=[]) %}
          {% for cargador in value_json %}
          {% set chargepointsList.chargepoints = chargepointsList.chargepoints + cargador.chargepoints %}
          {%- endfor %}
          {% set status = (chargepointsList.chargepoints | selectattr('serialOCPP','eq','melibmallo59') | list | first).status %}
          {%- if status == 'Busy' %}
            Ocupado
          {% elif status == 'Available' %}
            Libre
          {% elif status == 'OutOfOrder' %}
            Fuera de servicio
          {% else %}
            Desconocido
          {%- endif %}
