recorder:
  include:
    entities:
      - sensor.efergy_2577
      - sensor.energy_pvpc
      - sensor.energy_price

      - sensor.salon_switch_power
      - sensor.salon_switch_energy

      - sensor.comedor_switch_power
      - sensor.comedor_switch_energy

      - sensor.suite_switch_power
      - sensor.suite_switch_energy

      - sensor.escalera_switch_power
      - sensor.escalera_switch_energy
      
      - sensor.piscina_power
      - sensor.piscina_energy
      
      - climate.netatmo_general
      
      - sensor.co2_intensity
      - sensor.grid_fossil_fuel_percentage
logbook:
  exclude:
    entities:
      - sensor.efergy_2577

sensor:
  - platform: integration 
    source: sensor.efergy_2577
    name: energy_spent
    unit_prefix: k
    round: 2