recorder:
  include:
    entities:
      - binary_sensor.lavadora_status
      - binary_sensor.lavadora_status_high_power
      - sensor.lavadora_power
      - sensor.lavadora_energy
      - switch.lavadora

template:
  - binary_sensor:
      - name: lavadora_status
        unique_id: lavadora_status
        availability: >
          {{ is_number(states('sensor.lavadora_power')) }}
        state: >
          {{ states('sensor.lavadora_power') | float > 5 }}
        delay_off: "00:05:00"
        icon: >
          {% if states('sensor.lavadora_power') | float(0) > 5 %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}
        attributes:
          power: >
            {{ states('sensor.lavadora_power') | float(0) | round(0) }} W

      # Washing machine uses more power during first 30 mins
      # because it is normally heating the water.
      # This sensor remains ON during those first 30 minutes,
      # even if instantaneous power temporarily drops.
      # This is useful to allow to start other appliances while the washing machine has not finished and it's not using high power.
      - name: lavadora_status_high_power
        unique_id: lavadora_status_high_power
        state: >
          {% if is_state('binary_sensor.lavadora_status', 'on') %}
            {{
              (as_timestamp(now()) -
               as_timestamp(states.binary_sensor.lavadora_status.last_changed))
              <= 1800
            }}
          {% else %}
            false
          {% endif %}
        icon: >
          {% if is_state('binary_sensor.lavadora_status_high_power', 'on') %}
            mdi:lightning-bolt
          {% else %}
            mdi:lightning-bolt-outline
          {% endif %}
