recorder:
  include:
    entities:
      - sensor.climatizacion_primera_planta_aire_acondicionado_energia
      - sensor.climatizacion_primera_planta_aire_acondicionado_potencia

      - binary_sensor.climatizacion_primera_planta_aire_acondicionado_activo

template:
  - binary_sensor:
      - name: "Climatización primera planta aire acondicionado activo"
        unique_id: climatizacion_primera_planta_aire_acondicionado_activo
        availability: >
          {{ is_number(states('sensor.climatizacion_primera_planta_aire_acondicionado_potencia')) }}
        state: >
          {{ states('sensor.climatizacion_primera_planta_aire_acondicionado_potencia') | float > 50 }}
        delay_off: "00:15:00"
        icon: >
          {% if states('sensor.climatizacion_primera_planta_aire_acondicionado_potencia') | float(0) > 50 %}
            mdi:hvac
          {% else %}
            mdi:hvac-off
          {% endif %}
        attributes:
          power: >
            {{ states('sensor.climatizacion_primera_planta_aire_acondicionado_potencia') | float(0) | round(0) }} W
