recorder:
  include:
    entities:
      - sensor.fronius_smartmeter_energy_real_produced
      - sensor.fronius_smartmeter_energy_real_consumed
      - sensor.fronius_inverter_energy_total
      - sensor.fronius_solarnet_power_grid
      - sensor.fronius_solarnet_power_load
      - sensor.solarnet_power_grid_export

      - sensor.energy_power_photovoltaics
      - sensor.energy_power_house
      - sensor.energy_net_balance_hour
      - sensor.energy_net_balance

      - sensor.salon_principal_potencia
      - sensor.salon_principal_energia

      - sensor.comedor_principal_potencia
      - sensor.comedor_principal_energia

      - sensor.suite_principal_potencia
      - sensor.suite_principal_energia

      - sensor.escalera_principal_potencia
      - sensor.escalera_principal_energia

      - sensor.piscina_medidor_consumo_potencia
      - sensor.piscina_medidor_consumo_energia

      - climate.recibidor

      - sensor.co2_intensity
      - sensor.grid_fossil_fuel_percentage
      - sensor.hokuslaptop_remaining_battery

logbook:
  exclude:
    entity_globs:
      - sensor.fronius_*
template:
  - sensor:
      # The raw Fronius photovoltaic state goes to unknown after dark, so force it to zero
      - name: energy_power_photovoltaics
        unique_id: "energy_power_photovoltaics"
        device_class: power
        state_class: measurement
        unit_of_measurement: "W"
        state: "{{ states('sensor.fronius_solarnet_power_photovoltaics')|float(0) }}"

      # Total home instant power
      - name: energy_power_house
        unique_id: "energy_power_house"
        device_class: power
        state_class: measurement
        unit_of_measurement: "W"
        state: "{{ 0 - states('sensor.fronius_solarnet_power_load')|float(0)|round(1) }}"

utility_meter:
  energy_grid_today:
    unique_id: energy_grid_today
    source: sensor.fronius_smartmeter_energy_real_consumed
    cycle: daily
    tariffs:
      - Punta
      - Llana
      - Valle
