recorder:
  include:
    entities:
      - sensor.qnapups_status_spanish

      - binary_sensor.energy_home_status

template:
  - binary_sensor:
    - name: energy_home_status
      device_class: plug
      # Takes into consideration: OL, OL CHRG, OL LB, OL CHRG LB
      state: "{{ 'OL' in states('sensor.qnapups_status_data') }}"
      delay_off:
        seconds: 30
  - sensor:
    - name: qnapups_status_spanish
      state: >-
          {%- if is_state('sensor.qnapups_status_data', 'OL') %}
            Normal
          {% elif is_state('sensor.qnapups_status_data', 'OL LB') %}
            Normal batería baja
          {% elif is_state('sensor.qnapups_status_data', 'OL CHRG') %}
            Cargando
          {% elif is_state('sensor.qnapups_status_data', 'OL CHRG LB') %}
            Cargando batería baja
          {% elif is_state('sensor.qnapups_status_data', 'OB DISCHRG') %}
            Batería
          {% elif is_state('sensor.qnapups_status_data', 'LB DISCHRG') %}
            Batería baja
          {% elif is_state('sensor.qnapups_status_data', 'RB') %}
            Reemplazar batería
          {% else %}
            Desconocido
          {%- endif %}
