recorder:
  include:
    entities:
      - binary_sensor.cargador_ev_status
      - sensor.cargador_ev_power
      - sensor.cargador_ev_energy_calc
#      - input_number.cargador_ev_on_threshold
#      - input_number.cargador_ev_on_delay
#      - input_number.cargador_ev_off_threshold
#      - input_number.cargador_ev_off_delay

logbook:
  exclude:
    entities:
      - sensor.cargador_ev_power
      - sensor.cargador_ev_energy_calc
#      - input_number.cargador_ev_on_threshold
#      - input_number.cargador_ev_off_threshold
#      - input_number.cargador_ev_off_delay

binary_sensor:
  - platform: threshold
    name: cargador_ev_status
    entity_id: sensor.cargador_ev_power
    upper: 5
    device_class: power

sensor:
  # Sensor needed due to a bug in the device that shows negative value
  # when the plug is turned on but no power is consumed
  - platform: integration 
    source: sensor.cargador_ev_power
    name: cargador_ev_energy_calc
    unit_prefix: k
    method: left
    round: 2

utility_meter:
  cargador_ev_today_energy:
    source: sensor.cargador_ev_energy_calc
    cycle: daily

  cargador_ev_hour_energy:
    source: sensor.cargador_ev_energy_calc
    cycle: hourly

input_boolean:
  cargador_ev_automatic_turn_off:
    name: Desconexión automática

input_number:
  # Grid power (negative exporting / positive importing) to turn on EV charger.
  # i.e: -1300 Means turn on EV charger when exporting 1300W to the grid.
  cargador_ev_on_threshold:
    name: 'Potencia para encendido'
    unit_of_measurement: 'W'
    icon: 'mdi:lightning-bolt'
    initial: -1300
    min: -3000
    max: 0
    step: 100
  # Max power consumed from grid allowed.
  # If the consumed power is over this threshold for x minutes, the EV charger will be turned off by an automation.
  cargador_ev_off_threshold:
    name: 'Consumo para apagado'
    unit_of_measurement: 'W'
    icon: 'mdi:lightning-bolt'
    initial: 500
    min: 0
    max: 2000
    step: 100
  cargador_ev_on_delay:
    name: 'Retardo encendido'
    unit_of_measurement: 'mins'
    icon: 'mdi:clock-in'
    initial: 3
    min: 0
    max: 60
    step: 1

  cargador_ev_off_delay:
    name: 'Retardo apagado'
    unit_of_measurement: 'mins'
    icon: 'mdi:clock-out'
    initial: 10
    min: 0
    max: 60
    step: 2
