recorder:
  include:
    entities:
      - sensor.ladron_salon_power
      - sensor.ladron_salon_energy_calc

sensor:
  # Sensor needed due to a bug in the device that shows negative value
  # when the plug is turned on but no power is consumed
  - platform: integration 
    source: sensor.ladron_salon_power
    name: ladron_salon_energy_calc
    unit_prefix: k
    round: 2