recorder:
  include:
    entities:
      - sensor.energy_grid_today_punta
      - sensor.energy_grid_today_punta_cost
      - sensor.energy_grid_today_llana
      - sensor.energy_grid_today_llana_cost
      - sensor.energy_grid_today_valle
      - sensor.energy_grid_today_valle_cost

      - sensor.energy_pvpc
      - sensor.energy_price_buy
      - sensor.energy_price_sell

      - sensor.energy_tariff

sensor:
  - platform: mqtt
    state_topic: 'home/sensor/energy/tariff'
    name: energy_tariff

  - platform: mqtt
    state_topic: 'home/sensor/energy/price/buy'
    name: energy_price_buy
    unique_id: energy_price_buy
    state_class: 'measurement'
    unit_of_measurement: '€/kWh'
    icon: 'mdi:currency-eur'

  - platform: mqtt
    state_topic: 'home/sensor/energy/price/sell'
    name: energy_price_sell
    unique_id: energy_price_sell
    state_class: 'measurement'
    unit_of_measurement: '€/kWh'
    icon: 'mdi:currency-eur'

binary_sensor:
  - platform: template
    sensors:
      # Valle full day tariff on weekends and national fix date holidays (local holidays and easter excluded)
      # 1 de enero (Año Nuevo)
      # 1 de mayo (Fiesta del Trabajo)
      # 12 de octubre (Fiesta Nacional de España)
      # 1 de noviembre (Todos los Santos)
      # 6 de diciembre (Día de la Constitución Española)
      # 8 de diciembre (Inmaculada Concepción)
      # 25 de diciembre (Natividad del Señor)
      energy_valle_full_day_tariff:
        value_template: >- 
            {{now().weekday() in (5,6) or
            (now().day == 1 and now().month == 1) or
            (now().day == 1 and now().month == 5) or
            (now().day == 12 and now().month == 10) or
            (now().day == 1 and now().month == 11) or
            (now().day == 6 and now().month == 12) or
            (now().day == 8 and now().month == 12) or
            (now().day == 25 and now().month == 12)}}

utility_meter:
  energy_grid_today:
    source: sensor.fronius_smartmeter_energy_real_consumed
    cycle: daily
    tariffs:
      - Punta
      - Llana
      - Valle 
