recorder:
  include:
    entities:
      - binary_sensor.secadora_status
      - sensor.secadora_power
      - sensor.secadora_energy_calc

template:
  - binary_sensor:
      - name: secadora_status
        state: "{{ states('sensor.secadora_power') | float > 5 }}"
        delay_off: "0:05:00"
        icon: >-
          {% if states('sensor.secadora_power') | float > 5 -%}
            mdi:tumble-dryer
          {%- else -%}
            mdi:tumble-dryer-off
          {%- endif %}