recorder:
  include:
    entities:
      - binary_sensor.cocina_lavavajillas_estado
      - sensor.cocina_lavavajillas_potencia
      - sensor.cocina_lavavajillas_energia

template:
  - binary_sensor:
      - name: Cocina lavavajillas estado
        unique_id: cocina_lavavajillas_estado
        availability: >
          {{ is_number(states('sensor.cocina_lavavajillas_potencia')) }}
        state: >
          {{ states('sensor.cocina_lavavajillas_potencia') | float > 5 }}
        delay_off: "00:05:00"
        icon: >
          {% if states('sensor.cocina_lavavajillas_potencia') | float(0) > 5 %}
            mdi:dishwasher
          {% else %}
            mdi:dishwasher-off
          {% endif %}
        attributes:
          potencia: >
            {{ states('sensor.cocina_lavavajillas_potencia') | float(0) | round(0) }} W
