recorder:
  include:
    entities:
      - switch.salon_regleta
      - sensor.salon_regleta_potencia
      - sensor.salon_regleta_potencia_filtrada
      - sensor.salon_regleta_energia

template:
  - trigger:
      - platform: state
        entity_id: sensor.salon_regleta_potencia

    sensor:
      - name: "Salon regleta potencia filtrada"
        unique_id: salon_regleta_potencia_filtrada
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        availability: >
          {{ trigger.to_state is not none }}
        state: >
          {% set p = trigger.to_state.state | float(none) %}
          {% if p is not none and 0 <= p <= 3800 %}
            {{ p }}
          {% else %}
            {{ this.state }}
          {% endif %}
