recorder:
  include:
    entities:
      - binary_sensor.secadora_status
      - sensor.secadora_power
      - sensor.secadora_power_filtered
      - sensor.secadora_energy_calc

template:
  - binary_sensor:
      - name: secadora_status
        unique_id: secadora_status
        state: "{{ states('sensor.secadora_power') | float(default=0) > 5 }}"
        delay_off: "0:05:00"
        icon: >-
          {% if states('sensor.secadora_power') | float(default=0) > 5 -%}
            mdi:tumble-dryer
          {%- else -%}
            mdi:tumble-dryer-off
          {%- endif %}
        attributes:
          power: "{{ states('sensor.secadora_power_filtered') }}W"

sensor:
  - platform: filter
    name: secadora_power_filtered
    unique_id: secadora_power_filtered
    entity_id: sensor.secadora_power
    filters:
      - filter: outlier
        window_size: 4
        radius: 10000.0
