recorder:
  include:
    entities:
      - binary_sensor.lavaplatos_status
      - sensor.lavaplatos_power
      - sensor.lavaplatos_power_filtered
      - sensor.lavaplatos_energy_calc

template:
  - binary_sensor:
      - name: lavaplatos_status
        unique_id: lavaplatos_status
        state: "{{ states('sensor.lavaplatos_power') | float(default=0) > 5 }}"
        delay_off: "0:05:00"
        icon: >-
          {% if states('sensor.lavaplatos_power') | float(default=0) > 5 -%}
            mdi:dishwasher
          {%- else -%}
            mdi:dishwasher-off
          {%- endif %}
        attributes:
          power: "{{ states('sensor.lavaplatos_power_filtered') }}W"

sensor:
  - platform: filter
    name: lavaplatos_power_filtered
    unique_id: lavaplatos_power_filtered
    entity_id: sensor.lavaplatos_power
    filters:
      - filter: outlier
        window_size: 4
        radius: 10000.0
