recorder:
  include:
    entities:
      - binary_sensor.lavaplatos_status
      - sensor.lavaplatos_switch_0_power
      - sensor.lavaplatos_switch_0_energy

template:
  - binary_sensor:
      - name: "Estado Lavaplatos"
        unique_id: lavaplatos_status
        availability: >
          {{ is_number(states('sensor.lavaplatos_switch_0_power')) }}
        state: >
          {{ states('sensor.lavaplatos_switch_0_power') | float > 5 }}
        delay_off: "00:05:00"
        icon: >
          {% if states('sensor.lavaplatos_switch_0_power') | float(0) > 5 %}
            mdi:dishwasher
          {% else %}
            mdi:dishwasher-off
          {% endif %}
        attributes:
          power: >
            {{ states('sensor.lavaplatos_switch_0_power') | float(0) | round(0) }} W
