recorder:
  include:
    entities:
      - sensor.efergy_2577
      - sensor.qnapups_status_spanish
      - sensor.qnapups_status_data
      - sensor.pvpcdha
      - sensor.pvpcdha_access_toll
      - sensor.energy_home_hourly_cost
      - sensor.energy_home_daily_cost
      - sensor.energy_home_monthly_cost
      - sensor.energy_home_monthly_valle_pct
      - binary_sensor.energy_home_status
      - sensor.energy_tariff

logbook:
  exclude:
    entities:
      - sensor.efergy_2577

sensor:
  - platform: efergy
    app_token: !secret efergy_app_token
    utc_offset: 2
    monitored_variables:
      - type: current_values

  - platform: integration 
    source: sensor.efergy_2577
    name: energy_spent
    unit_prefix: k
    round: 2

  - platform: template
    sensors:
      energy_price_valle_access_toll:
        friendly_name: 'Peaje acceso valle'
        value_template: 0.002215
        unit_of_measurement: '€/kWh'
      energy_price_pico_access_toll:
        friendly_name: 'Peaje acceso valle punta'
        value_template: 0.062012
        unit_of_measurement: '€/kWh'
      energy_price_electriciy_tax:
        friendly_name: 'Impuesto sobre la electricidad'
        value_template: 5.1127
        unit_of_measurement: '%'
      energy_price_vat:
        friendly_name: 'IVA'
        value_template: 21
        unit_of_measurement: '%'
      qnapups_status_spanish:
        value_template: >-
          {%- if is_state('sensor.qnapups_status_data', 'OL') %}
            Normal
          {% elif is_state('sensor.qnapups_status_data', 'OL LB') %}
            Normal batería baja
          {% elif is_state('sensor.qnapups_status_data', 'OL CHRG') %}
            Cargando
          {% elif is_state('sensor.qnapups_status_data', 'OL CHRG LB') %}
            Cargando batería baja
          {% elif is_state('sensor.qnapups_status_data', 'OB DISCHRG') %}
            Batería
          {% elif is_state('sensor.qnapups_status_data', 'LB DISCHRG') %}
            Batería baja
          {% elif is_state('sensor.qnapups_status_data', 'RB') %}
            Reemplazar batería
          {% else %}
            Desconocido
          {%- endif %}
      pvpcdha_access_toll:
        friendly_name: "Precio energía con peaje"
        unit_of_measurement: '€/kWh'
        icon_template: "mdi:cash-multiple"
        value_template: >- 
            {%if states.sensor.pvpcdha.state %}
              {% if is_state('sensor.energy_tariff', 'Pico') %}
                {{ ((states.sensor.energy_price_pico_access_toll.state | float) + (states.sensor.pvpcdha.state | float)) | round(5) }}
              {% elif is_state('sensor.energy_tariff', 'Valle') %}
                {{ ((states.sensor.energy_price_valle_access_toll.state | float) + (states.sensor.pvpcdha.state | float)) | round(5) }}
              {% else %}
                unknown
              {% endif %}
            {% else %}
              unknown
            {% endif %}
      energy_cost_hour:
        friendly_name: "Coste energía (hora en curso)"
        unit_of_measurement: '€'
        icon_template: "mdi:cash-multiple"
        value_template: "{%if states.sensor.pvpcdha.state %}{{ ((states.sensor.energy_home_hourly.state | float) * (states.sensor.pvpcdha.state | float)) | round(5) }}{% else %}unknown{% endif %}"
      energy_home_daily_valle_pct:
        friendly_name: "Proporción diaria"
        unit_of_measurement: '%'
        icon_template: "mdi:label-percent"
        value_template: "{{ (((states.sensor.energy_home_daily_valle.state | float))/(((states.sensor.energy_home_daily_pico.state | float) + (states.sensor.energy_home_daily_valle.state | float))) * 100)  | round(1) }}"
      energy_home_monthly_valle_pct:
        friendly_name: "Proporción mensual"
        unit_of_measurement: '%'
        icon_template: "mdi:label-percent"
        value_template: "{{ (((states.sensor.energy_home_monthly_valle.state | float))/(((states.sensor.energy_home_monthly_pico.state | float) + (states.sensor.energy_home_monthly_valle.state | float))) * 100)  | round(1) }}"

#  - platform: mqtt
#    state_topic: 'home/sensor/energy/tariff'
#    name: energy_tariff

  - platform: mqtt
    state_topic: 'home/sensor/energy/tariff'
    name: energy_tariff

binary_sensor:
  - platform: template
    sensors:
      # Valle full day tariff on weekends and national fix date holidays (local holidays and easter excluded)
      # 1 de enero (Año Nuevo)
      # 1 de mayo (Fiesta del Trabajo)
      # 12 de octubre (Fiesta Nacional de España)
      # 1 de noviembre (Todos los Santos)
      # 6 de diciembre (Día de la Constitución Española)
      # 8 de diciembre (Inmaculada Concepción)
      # 25 de diciembre (Natividad del Señor)
      energy_valle_full_day_tariff:
        value_template: >- 
            {{now().weekday() in (5,6) or
            (now().day == 1 and now().month == 1) or
            (now().day == 1 and now().month == 5) or
            (now().day == 12 and now().month == 10) or
            (now().day == 1 and now().month == 11) or
            (now().day == 6 and now().month == 12) or
            (now().day == 8 and now().month == 12) or
            (now().day == 25 and now().month == 12)}}
        
      energy_home_status:
        device_class: plug
        # Takes into consideration: OL, OL CHRG, OL LB, OL CHRG LB
        value_template: "{{ 'OL' in states('sensor.qnapups_status_data') }}"
        delay_off:
          seconds: 30

utility_meter:
  energy_home_hourly:
    source: sensor.energy_spent
    cycle: hourly 
  energy_home_daily:
    source: sensor.energy_spent
    cycle: daily 
    tariffs:
      - Punta
      - Llana
      - Valle
  energy_home_monthly:
    source: sensor.energy_spent
    cycle: monthly
    offset:
      days: 5
    tariffs:
      - Punta
      - Llana
      - Valle
  energy_home_hourly_cost:
    source: sensor.energy_cost_hour
    cycle: hourly
  energy_home_daily_cost:
    source: sensor.energy_cost_hour
    cycle: daily
  energy_home_monthly_cost:
    source: sensor.energy_cost_hour
    cycle: monthly
    offset:
      days: 5
