recorder:
  include:
    entities:
      - binary_sensor.lavadora_status
      - sensor.lavadora_power
      - sensor.lavadora_energy_calc
      - sensor.lavadora_power_statistics

template:
  - binary_sensor:
      - name: lavadora_status
        state: "{{ states('sensor.lavadora_power') | float > 5 }}"
        delay_off: "0:05:00"
        icon: >-
          {% if states('sensor.lavadora_power') | float > 5 -%}
            mdi:washing-machine
          {%- else -%}
            mdi:washing-machine-off
          {%- endif %}

sensor:
  # Sensor needed due to a bug in the device that shows negative value
  # when the plug is turned on but no power is consumed
  - platform: integration 
    source: sensor.lavadora_power
    name: lavadora_energy_calc
    unit_prefix: k
    method: left
    round: 2

  - platform: statistics
    name: lavadora_power_statistics
    entity_id: sensor.lavadora_power
    state_characteristic: mean