recorder:
  include:
    entities:
      - binary_sensor.secadora_status
      - sensor.secadora_power
      - sensor.secadora_energy
      - switch.secadora

template:
  - binary_sensor:
      - name: secadora_status
        unique_id: secadora_status
        state: "{{ states('sensor.secadora_power') | float(default=0) > 5 }}"
        delay_off: "0:05:00"
        icon: >-
          {% if states('sensor.secadora_power') | float(default=0) > 5 -%}
            mdi:tumble-dryer
          {%- else -%}
            mdi:tumble-dryer-off
          {%- endif %}
        attributes:
          power: "{{ states('sensor.secadora_power') }}W"
