recorder:
  include:
    entities:
      - sensor.efergy_2577
      - sensor.qnapups_status_spanish
      - sensor.qnapups_status_data
      - sensor.energy_pvpc

      - sensor.energy_grid_today_punta
      - sensor.energy_grid_today_punta_cost
      - sensor.energy_grid_today_llana
      - sensor.energy_grid_today_llana_cost
      - sensor.energy_grid_today_valle
      - sensor.energy_grid_today_valle_cost

      - sensor.salon_switch_power
      - sensor.salon_switch_energy_spent
      - sensor.salon_switch_energy_today

      - sensor.comedor_switch_power
      - sensor.comedor_switch_energy_spent
      - sensor.comedor_switch_energy_today

      - sensor.suite_switch_power
      - sensor.suite_switch_energy_spent
      - sensor.suite_switch_energy_today

      - sensor.escalera_switch_power
      - sensor.escalera_switch_energy_spent
      - sensor.escalera_switch_energy_today

      - binary_sensor.energy_home_status
      - sensor.energy_tariff

logbook:
  exclude:
    entities:
      - sensor.efergy_2577

sensor:
  - platform: efergy
    app_token: !secret efergy_app_token
    utc_offset: 2
    monitored_variables:
      - type: current_values

  - platform: integration 
    source: sensor.efergy_2577
    name: energy_spent
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.salon_switch_power
    name: salon_switch_energy_spent
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.comedor_switch_power
    name: comedor_switch_energy_spent
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.suite_switch_power
    name: suite_switch_energy_spent
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.escalera_switch_power
    name: escalera_switch_energy_spent
    unit_prefix: k
    round: 2

  - platform: template
    sensors:
      qnapups_status_spanish:
        value_template: >-
          {%- if is_state('sensor.qnapups_status_data', 'OL') %}
            Normal
          {% elif is_state('sensor.qnapups_status_data', 'OL LB') %}
            Normal batería baja
          {% elif is_state('sensor.qnapups_status_data', 'OL CHRG') %}
            Cargando
          {% elif is_state('sensor.qnapups_status_data', 'OL CHRG LB') %}
            Cargando batería baja
          {% elif is_state('sensor.qnapups_status_data', 'OB DISCHRG') %}
            Batería
          {% elif is_state('sensor.qnapups_status_data', 'LB DISCHRG') %}
            Batería baja
          {% elif is_state('sensor.qnapups_status_data', 'RB') %}
            Reemplazar batería
          {% else %}
            Desconocido
          {%- endif %}

  - platform: mqtt
    state_topic: 'home/sensor/energy/tariff'
    name: energy_tariff

binary_sensor:
  - platform: template
    sensors:
      # Valle full day tariff on weekends and national fix date holidays (local holidays and easter excluded)
      # 1 de enero (Año Nuevo)
      # 1 de mayo (Fiesta del Trabajo)
      # 12 de octubre (Fiesta Nacional de España)
      # 1 de noviembre (Todos los Santos)
      # 6 de diciembre (Día de la Constitución Española)
      # 8 de diciembre (Inmaculada Concepción)
      # 25 de diciembre (Natividad del Señor)
      energy_valle_full_day_tariff:
        value_template: >- 
            {{now().weekday() in (5,6) or
            (now().day == 1 and now().month == 1) or
            (now().day == 1 and now().month == 5) or
            (now().day == 12 and now().month == 10) or
            (now().day == 1 and now().month == 11) or
            (now().day == 6 and now().month == 12) or
            (now().day == 8 and now().month == 12) or
            (now().day == 25 and now().month == 12)}}

      energy_home_status:
        device_class: plug
        # Takes into consideration: OL, OL CHRG, OL LB, OL CHRG LB
        value_template: "{{ 'OL' in states('sensor.qnapups_status_data') }}"
        delay_off:
          seconds: 30

utility_meter:
  energy_grid_today:
    source: sensor.energy_spent
    cycle: daily
    tariffs:
      - Punta
      - Llana
      - Valle 
  salon_switch_energy_today:
    source: sensor.salon_switch_energy_spent
    cycle: daily
  comedor_switch_energy_today:
    source: sensor.comedor_switch_energy_spent
    cycle: daily
  suite_switch_energy_today:
    source: sensor.suite_switch_energy_spent
    cycle: daily
  escalera_switch_energy_today:
    source: sensor.escalera_switch_energy_spent
    cycle: daily
