recorder:
  include:
    entities:
      - binary_sensor.bomba_agua_status
      - sensor.bomba_agua_power
      - sensor.bomba_agua_energy_calc

template:
  - binary_sensor:
      - name: bomba_agua_status
        state: "{{ states('sensor.bomba_agua_power') | float > 5 }}"
        icon: >-
          {% if states('sensor.bomba_agua_power') | float > 5 -%}
            mdi:water-pump
          {%- else -%}
            mdi:water-pump-off
          {%- endif %}