recorder:
  include:
    entity_globs:
      - sensor.fronius_*
    entities:
#      - sensor.efergy_2577

      - sensor.energy_power_photovoltaics
      - sensor.energy_power_house
      - sensor.energy_power_grid_import
      - sensor.energy_net_balance_hour
      - sensor.energy_net_balance

      - sensor.salon_switch_power
      - sensor.salon_switch_energy

      - sensor.comedor_switch_power
      - sensor.comedor_switch_energy

      - sensor.suite_switch_power
      - sensor.suite_switch_energy

      - sensor.escalera_switch_power
      - sensor.escalera_switch_energy
      
      - sensor.piscina_power
      - sensor.piscina_energy
      
      - climate.netatmo_general
      
      - sensor.co2_intensity
      - sensor.grid_fossil_fuel_percentage
      
      - sensor.energy_next_hour
      - sensor.energy_current_hour
      - sensor.energy_production_today
      - sensor.energy_production_tomorrow
      
      - sensor.power_production_next_12hours
      - sensor.power_production_next_24hours
      - sensor.power_production_next_hour
      - sensor.power_production_now
      
logbook:
  exclude:
#    entities:
#      - sensor.efergy_2577
    entity_globs:
      - sensor.fronius_*
sensor:
  - platform: template
    sensors:
      # The raw Fronius photovoltaic state goes to unknown after dark, so force it to zero
      energy_power_photovoltaics:
        device_class: power
        friendly_name: "Producción fotovoltáica"
        unit_of_measurement: "W"
        value_template: "{{ states('sensor.fronius_solarnet_power_photovoltaics')|float }}"

      energy_power_house:
        device_class: power
        friendly_name: "Potencia casa"
        unit_of_measurement: "W"
        value_template: "{{ 0 - states('sensor.fronius_solarnet_power_load')|float|round(1) }}"

      # The raw grid power is negative if exporting and positive if importing
      energy_power_grid_import:
        device_class: power
        friendly_name: "Potencia red"
        unit_of_measurement: "W"
        value_template: "{{ [states('sensor.fronius_solarnet_power_grid')|float, 0]|max }}"

  - platform: integration
    source: sensor.fronius_solarnet_power_grid
    name: energy_net_balance
    unit_prefix: k
    round: 2

utility_meter:
  energy_net_balance_hour:
    source: sensor.energy_net_balance
    cycle: hourly
    net_consumption: true
