recorder:
  include:
    entities:
      - binary_sensor.coladuria_lavadora_estado
      - binary_sensor.coladuria_lavadora_estado_alto_consumo
      - sensor.coladuria_lavadora_potencia
      - sensor.coladuria_lavadora_energia
      - switch.coladuria_lavadora

template:
  - binary_sensor:
      - name: Coladuria lavadora estado
        unique_id: coladuria_lavadora_estado
        availability: >
          {{ is_number(states('sensor.coladuria_lavadora_potencia')) }}
        state: >
          {{ states('sensor.coladuria_lavadora_potencia') | float > 5 }}
        delay_off: "00:05:00"
        icon: >
          {% if states('sensor.coladuria_lavadora_potencia') | float(0) > 5 %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}
        attributes:
          potencia: >
            {{ states('sensor.coladuria_lavadora_potencia') | float(0) | round(0) }} W

      # La lavadora suele consumir más durante los primeros 30 minutos al
      # calentar el agua. Este sensor permanece activo en ese periodo aunque
      # la potencia instantánea baje temporalmente.
      - name: Coladuria lavadora estado alto consumo
        unique_id: coladuria_lavadora_estado_alto_consumo
        state: >
          {% if is_state('binary_sensor.coladuria_lavadora_estado', 'on') %}
            {{
              (as_timestamp(now()) -
               as_timestamp(states.binary_sensor.coladuria_lavadora_estado.last_changed))
              <= 1800
            }}
          {% else %}
            false
          {% endif %}
        icon: >
          {% if is_state('binary_sensor.coladuria_lavadora_estado_alto_consumo', 'on') %}
            mdi:lightning-bolt
          {% else %}
            mdi:lightning-bolt-outline
          {% endif %}
