recorder:
  include:
    entities:
      - binary_sensor.lavaplatos_status
      - sensor.lavaplatos_power
      - sensor.lavaplatos_energy_calc

template:
  - binary_sensor:
      - name: lavaplatos_status
        state: "{{ states('sensor.lavaplatos_power') | float > 5 }}"
        delay_off: "0:05:00"
        icon: >-
          {% if states('sensor.lavaplatos_power') | float > 5 -%}
            mdi:dishwasher
          {%- else -%}
            mdi:dishwasher-off
          {%- endif %}