recorder:
  include:
    entities:
      - binary_sensor.cargador_ev_status
      - sensor.cargador_ev_power
      - sensor.cargador_ev_energy_calc

binary_sensor:
  - platform: threshold
    name: cargador_ev_status
    entity_id: sensor.cargador_ev_power
    upper: 5
    device_class: power

sensor:
  # Sensor needed due to a bug in the device that shows negative value
  # when the plug is turned on but no power is consumed
  - platform: integration 
    source: sensor.cargador_ev_power
    name: cargador_ev_energy_calc
    unit_prefix: k
    round: 2

utility_meter:
  cargador_ev_today_energy:
    source: sensor.cargador_ev_energy_calc
    cycle: daily

  cargador_ev_hour_energy:
    source: sensor.cargador_ev_energy_calc
    cycle: hourly

input_number:
  # Max power consumed from grid allowed.
  # If this threshold is broken for x minutes it, the charger will be turned off by an automation
  cargador_ev_off_threshold:
    name: 'Potencia apagado'
    unit_of_measurement: 'W'
    icon: 'mdi:lightning-bolt'
    initial: 500
    min: 0
    max: 2000
    step: 50
  # Estimated power generated to turn on tha car charger.
  cargador_ev_on_threshold:
    name: 'Potencia encendido'
    unit_of_measurement: 'W'
    icon: 'mdi:lightning-bolt'
    initial: 1900
    min: 0
    max: 2500
    step: 100
