recorder:
  include:
    entities:
      - sensor.energy_grid_today_punta
      - sensor.energy_grid_today_punta_cost
      - sensor.energy_grid_today_llana
      - sensor.energy_grid_today_llana_cost
      - sensor.energy_grid_today_valle
      - sensor.energy_grid_today_valle_cost

      - sensor.energy_pvpc
      - sensor.energy_price_buy
      - sensor.energy_price_sell

      - sensor.energy_tariff

mqtt:
  sensor:
    - state_topic: 'home/sensor/energy/tariff'
      name: energy_tariff

    - state_topic: 'home/sensor/energy/price/buy'
      name: energy_price_buy
      unique_id: energy_price_buy
      state_class: 'measurement'
      unit_of_measurement: '€/kWh'
      icon: 'mdi:currency-eur'

    - state_topic: 'home/sensor/energy/price/sell'
      name: energy_price_sell
      unique_id: energy_price_sell
      state_class: 'measurement'
      unit_of_measurement: '€/kWh'
      icon: 'mdi:currency-eur'
