recorder:
  include:
    entities:
      - cover.outside_fence
      - input_button.barrera


template:
  - sensor:
      # Shelly 1 Plus sensor state (off: fence closed, on: fence open)
    - name: outside_fence_sensor_state
      state: >-
          {%- if is_state('binary_sensor.barrera_estado', 'on') %}
            abierta
          {% else %}
            cerrada
          {% endif %}

  - cover:
      - name: outside_fence
        unique_id: outside_fence
        device_class: gate
        state: "{{ is_state('binary_sensor.barrera_estado', 'on') }}"
        open_cover:
          action: switch.turn_on
          data:
            entity_id: switch.barrera
        close_cover:
          action: switch.turn_on
          data:
            entity_id: switch.barrera
        icon: >-
          {%- if is_state('binary_sensor.barrera_estado', 'on') %}
            mdi:gate-open
          {% else %}
            mdi:gate
          {% endif %}

#  - platform: mqtt
#    name: 'outside_fence'
#    state_topic: 'home/sensor/fence'
#    icon: mdi:garage
