recorder:
  include:
    domains:
      - light

light:
  - platform: group
    name: Luces exteriores
    entities:
      - light.barrera_derecha
      - light.barrera_izquierda
      - light.puerta_coladuria

  - platform: switch
    name: Salon principal
    entity_id: switch.salon_principal

  - platform: switch
    name: Comedor principal
    entity_id: switch.comedor_principal

  - platform: switch
    name: Suite principal
    entity_id: switch.suite_principal

  - platform: switch
    name: Escalera principal
    entity_id: switch.escalera_principal

  - platform: switch
    name: Lámpara salón
    entity_id: switch.salon_lampara

  - platform: group
    name: Luces interiores
    entities:
      - light.suite_principal
      - light.escalera_principal
      - light.salon_lampara
      - light.comedor_principal
      - light.salon_principal

  - platform: group
    name: Luces interiores modo dormir
    entities:
      - light.escalera_principal
      - light.salon_lampara
      - light.comedor_principal
      - light.salon_principal
