recorder:
  include:
    domains:
      - light

light:
  - platform: group
    name: Luces exteriores
    entities:
      - light.barrera_derecha
      - light.barrera_izquierda
      - light.puerta_coladuria

  - platform: switch
    name: salon_light
    entity_id: switch.salon_switch

  - platform: switch
    name: comedor_light
    entity_id: switch.comedor_switch

  - platform: switch
    name: suite_light
    entity_id: switch.suite_switch

  - platform: switch
    name: escalera_light
    entity_id: switch.escalera_switch

  - platform: switch
    name: entrance_hall_lamp_light
    entity_id: switch.entrance_hall_lamp_switch

  - platform: group
    name: Luces interiores
    entities:
      - light.suite_light
      - light.escalera_light
      - light.entrance_hall_lamp_light
      - light.comedor_light
      - light.salon_light

  - platform: group
    name: Luces interiores modo dormir
    entities:
      - light.escalera_light
      - light.entrance_hall_lamp_light
      - light.comedor_light
      - light.salon_light
