recorder:
  include:
    entity_globs:
      - sensor.hokusphone_*
      - binary_sensor.hokusphone_*
      - sensor.carlosphone_*
      - binary_sensor.carlosphone_*
      - sensor.geniphone_*
      - binary_sensor.geniphone_*

logbook:
  include:
    entities:
      - binary_sensor.hokusphone_android_auto
      - sensor.hokusphone_detected_activity
      - sensor.hokusphone_wifi_connection
      - sensor.carlosphone_detected_activity
      - sensor.carlosphone_wifi_connection
      - sensor.geniphone_wifi_ssid
  exclude:
    entity_globs:
      - sensor.hokusphone_*
      - sensor.carlosphone_*
      - sensor.geniphone_*

template:
  - binary_sensor:
      - name: "hokusphone_in_car_ioniq"
        state: >-
          {{ is_state("binary_sensor.hokusphone_android_auto", "on")
             and state_attr("sensor.hokusphone_bluetooth_connection", "connected_paired_devices") | select("search","IONIQ") | list | length > 0 }}
