recorder:
  include:
    entities:
      - binary_sensor.water_pump_status

binary_sensor:
  - platform: threshold
    name: water_pump_status
    entity_id: sensor.bomba_agua_power
    upper: 5
    device_class: power
