recorder:
  include:
    entities:
      - switch.despacho_wallpanel_cargador
      - sensor.despacho_wallpanel_bateria
      - binary_sensor.despacho_wallpanel_enchufado
      - switch.despacho_wallpanel_deteccion_de_movimiento
      - switch.despacho_wallpanel_pantalla
