# Infrared status for foscam cam in hall
- platform: command_line
  # Command used to get infrared status for a foscam camera:
  # 'curl -k --silent "https://<cam_host>:<cam_port>/cgi-bin/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=<username>&pwd=<password>" | grep -oP "(?<=infraLedState>).*?(?=</infraLedState>)"'
  command: !secret cam_hall_infrared_command
  name: cam_hall_infrared
  payload_on: '1'
  payload_off: '0'
  #sensor_class: light

# Infrared status for foscam cam in swimming pool
- platform: command_line
  # Command used to get infrared status for a foscam camera:
  # 'curl -k --silent "https://<cam_host>:<cam_port>/cgi-bin/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=<username>&pwd=<password>" | grep -oP "(?<=infraLedState>).*?(?=</infraLedState>)"'
  command: !secret cam_swimmingpool_infrared_command
  name: cam_swimmingpool_infrared
  payload_on: '1'
  payload_off: '0'
  #sensor_class: light

- platform: template
  sensors:
    ups_status_bs:
      sensor_class: 'light'
      value_template: "{{ states.sensor.nut_ups_status_data.state == 'OL' or states.sensor.nut_ups_status_data.state == 'OL CHRG' }}"
      entity_id:
        - sensor.nut_ups_status_data

- platform: mqtt
  state_topic: 'home/camera/recibidor/alarm'
  name: 'cam_hall_alarm'
  sensor_class: motion
  # 0: No alarm
  # 1: Alarm triggered
  value_template: >-
          {%- if value != "0" %}
              ON
          {% else %}
              OFF
          {%- endif %}

# Alarm status for foscam cam in swimming pool
- platform: mqtt
  state_topic: 'home/camera/piscina/alarm'
  name: 'cam_swimmingpool_alarm'
  sensor_class: motion
  # 0: No alarm
  # 1: Alarm triggered
  value_template: >-
          {%- if value != "0" %}
              ON
          {% else %}
              OFF
          {%- endif %}

# Alarm status for Linksys cam in caseta
- platform: mqtt
  state_topic: 'home/camera/caseta/alarm'
  name: 'cam_caseta_alarm'
  sensor_class: motion
  # 0: No alarm
  # 1: Alarm triggered
  value_template: >-
          {%- if value != "0" %}
              ON
          {% else %}
              OFF
          {%- endif %}

- binary_sensor:
  platform: template
  sensors:
    living_room_alarm:
      value_template: '{{ is_state("sensor.fibaro_system_fgms001_motion_sensor_burglar_6_10", "8") }}'
      sensor_class: motion
    living_room_tampering:
      value_template: '{{ is_state("sensor.fibaro_system_fgms001_motion_sensor_burglar_6_10", "3") }}'
      sensor_class: vibration