- platform: command_line
  switches:
    #Switch for Foscam Motion Detection
    cam_hall_motion_detection:
      # Command used:
      # 'curl -k "https://<camera_host>:<camera_port>/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&linkage=12&snapInterval=3&sensitivity=1&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=<camera_username>&pwd=<camera_password>"'
      command_on: !secret cam_hall_motion_detection_on
      # Command used:
      # 'curl -k "https://<camera_host>:<camera_port>/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&linkage=12&snapInterval=3&sensitivity=1&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=<camera_username>&pwd=<camera_password>"'
      command_off: !secret cam_hall_motion_detection_off
      # Command used:
      # 'curl -k --silent "https://<camera_host>:<camera_port>/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=<camera_username>&pwd=<camera_password>" | grep -oP "(?<=isEnable>).*?(?=</isEnable>)"'
      command_state: !secret cam_hall_motion_detection_state
      value_template: '{{ value == "1" }}'

- platform: command_line
  switches:
    #Switch for Foscam Motion Detection
    cam_swimmingpool_motion_detection:
      # Command used:
      # 'curl -k "https://<camera_host>:<camera_port>/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&linkage=12&snapInterval=3&sensitivity=1&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023&area3=1023&area4=1009&area5=992&area6=992&area7=1023&area8=1023&area9=1023&usr=<camera_username>&pwd=<camera_password>"'
      command_on: !secret cam_swimmingpool_motion_detection_on
      # Command used:
      # 'curl -k "https://<camera_host>:<camera_port>/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&linkage=12&snapInterval=3&sensitivity=1&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023&area3=1023&area4=1009&area5=992&area6=992&area7=1023&area8=1023&area9=1023&usr=<camera_username>&pwd=<camera_password>"'
      command_off: !secret cam_swimmingpool_motion_detection_off
      # Command used:
      # 'curl -k --silent "https://<camera_host>:<camera_port>/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=<camera_username>&pwd=<camera_password>" | grep -oP "(?<=isEnable>).*?(?=</isEnable>)"'
      command_state: !secret cam_swimmingpool_motion_detection_state
      value_template: '{{ value == "1" }}'

- platform: command_line
  switches:
    #Switch for Linksys WVC54GCA Motion Detection
    cam_caseta_motion_detection:
      # Command used:
      # 'curl --user <camera_username>:<camera_password> -k "http://<camera_host>:<camera_port>/adm/file.cgi?h_en_trig=1&todo=save"'
      command_on: !secret cam_caseta_motion_detection_on
      # Command used:
      # 'curl --user <camera_username>:<camera_password> -k "http://<camera_host>:<camera_port>/adm/file.cgi?h_en_trig=0&todo=save"'
      command_off: !secret cam_caseta_motion_detection_off
      # Command used:
      # 'curl --user <camera_username>:<camera_password> -k --silent "http://<camera_host>:<camera_port>/adm/file.cgi?next_file=event.htm" | grep -oP "(?<=<input type=\"Hidden\" name=\"h_en_trig\" value=\").*?(?=\">)"'
      command_state: !secret cam_caseta_motion_detection_state
      value_template: '{{ value == "1" }}'

- platform: mqtt
  name: 'holiday'
  state_topic: 'home/holiday/status'
  command_topic: 'home/holiday/status'
  payload_on: 'ON'
  payload_off: 'OFF'
  optimistic: false
  qos: 0
  retain: true

- platform: template
  switches:
    thermostat_status:
      entity_id: climate.termostato
      value_template: >-
        {%- if states.climate.termostato.attributes.temperature <= 11.5 %}
          off
        {% else %}
          on
        {%- endif %}
      turn_on:
        service: climate.set_away_mode
        entity_id: climate.termostato
        data:
          away_mode: false
      turn_off:
        service: climate.set_temperature
        entity_id: climate.termostato
        data:
          temperature: 11.5

- platform: template
  switches:
    thermostat_away_mode:
      entity_id: climate.termostato
      value_template: '{{ states.climate.termostato.attributes.away_mode }}'
      turn_on:
        service: climate.set_away_mode
        entity_id: climate.termostato
        data:
          away_mode: true
      turn_off:
        service: climate.set_away_mode
        entity_id: climate.termostato
        data:
          away_mode: false
