- id: "car_zone_ioniq_enters_cargador_palmanyola_violetes"
  alias: "Car - Zone - Ioniq enters Cargador Palmanyola Violetes"
  trigger:
    - platform: zone
      entity_id: device_tracker.car_ioniq
      zone: zone.cargador_palmanyola_violetes
      event: enter
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.car_ioniq_state_sensor
        state: "Encendido"
      - condition: numeric_state
        entity_id: sensor.car_ioniq_location_gps_accuracy
        below: 100
      - condition: numeric_state
        entity_id: sensor.car_ioniq_battery
        below: 50
  action:
    - service: mqtt.publish
      data:
        payload_template: >
          El cargador de la calle Violetas de Palmañola está {{ states.sensor.cargador_palmanyola_violetes.state }}
        retain: false
        topic: "phone/sensor/hokus/cmnd/say"
