- id: 'car_charge_turn_on_charger'
  alias: 'Car - Charge - Turn on charger'
  trigger:
    - platform: numeric_state
      entity_id: sensor.fronius_solarnet_power_grid
      below: input_number.cargador_ev_on_threshold
      for:
        minutes: "{{ states('input_number.cargador_ev_on_delay') | int }}"
  action:
    - service: switch.turn_on
      entity_id: switch.cargador_ev_switch
