- id: 'car_charge_turn_off_charger'
  alias: 'Car - Charge - Turn off charger'
  trigger:
    # When exit 'Valle' energy tariff
    - platform: state
      entity_id: sensor.energy_tariff
      from: 'Valle'
    # When consuming from grid more power than threshold for 'input_number.cargador_ev_off_delay' minutes
    - platform: numeric_state
      entity_id: sensor.fronius_solarnet_power_grid
      above: input_number.cargador_ev_off_threshold
      for:
        minutes: "{{ states('input_number.cargador_ev_off_delay') | int }}"
  # Only execute action when not in 'Valle' tariff and not in manual charge.
  # This is to allow to charge EV during 'Valle' tariff or when I've chosen to do a manual charge regardless the tariff.
  condition: "{{ states('sensor.energy_tariff') != 'Valle' and states('input_boolean.cargador_ev_manual_charge') == 'off'}}"
  action:
    - service: switch.turn_off
      entity_id: switch.cargador_ev_switch
