- id: 'Car - Charge - Turn off charger'
  alias: 'Car - Charge - Turn off charger'
  trigger:
    - platform: numeric_state
      entity_id: sensor.fronius_solarnet_power_grid
      above: input_number.cargador_ev_off_threshold
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.cargador_ev_switch
