- id: "car_notification_ioniq_charge_finishes"
  alias: "Car - Notification - Ioniq charge finishes"
  trigger:
    platform: state
    entity_id: sensor.car_ioniq_charger_charge_state
    from: "Cargando"
  action:
    - action: notify.telegram_hokusphone
      data:
        message: '🚘 Carga del Ioniq en casa detenida. Batería al {{states("sensor.car_ioniq_battery")}}%'
