- id: 'car_zone_ioniq_enters_cargador_paseo_mallorca'
  alias: 'Car - Zone - Ioniq enters Cargador Paseo Mallorca'
  trigger:
    - platform: zone
      entity_id: device_tracker.car_ioniq
      zone: zone.cargador_paseo_mallorca
      event: enter
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.car_ioniq_state_sensor
        state: 'Encendido'
      - condition: numeric_state
        entity_id: sensor.car_ioniq_location_gps_accuracy
        below: 100
  action:
    - service: mqtt.publish
      data:
        payload_template: >
          El cargador de Paseo Mallorca está {{ states.sensor.cargador_paseo_mallorca.state }}
        retain: false
        topic: 'phone/sensor/hokus/cmnd/say'
    - service: notify.telegram
      data_template:
        message: 'El cargador de Paseo Mallorca está {{ states.sensor.cargador_paseo_mallorca.state }}'