- id: 'Car - Notification - Ioniq charge finishes'
  alias: 'Car - Notification - Ioniq charge finishes'
  trigger:
    platform: state
    entity_id: sensor.car_ioniq_charger_charge_state
    from: 'Cargando'
    to: 'Listo'
  condition:
    condition: template
    value_template: "{{ state('sensor.cargador_ev_today_energy') is not none }}"
  action:
    - service: notify.telegram
      data_template:
        message: '🚘 Carga del Ioniq finalizada. {{state("sensor.cargador_ev_today_energy")}} kWh cargados.'
    - service: notify.slack
      data_template:
        message: ''
        data:
          blocks:
            - type: 'divider'
            - type: 'section'
              text:
                type: 'mrkdwn'
                text: ':car-electric: Carga del Ioniq finalizada. {{state("sensor.cargador_ev_today_energy")}} kWh cargados.'
            - type: 'divider'