- id: coche_cargador_ev_encender_tarifa_valle
  alias: "Coche - Cargador EV - Encender tarifa valle"
  trigger:
    # When electric tariff changes to 'Valle'
    platform: state
    entity_id: select.energy_grid_today
    to: "Valle"
  # Execute automation when:
  #  - Solar + Valle mode
  #  - EV charger is off
  condition:
    condition: and
    conditions:
      - alias: "Solar + Valle mode"
        condition: state
        entity_id: input_select.coladuria_cargador_ev_modo
        state: "Solar + Valle"
      - alias: "EV charger is off"
        condition: state
        entity_id: switch.coladuria_cargador_ev
        state: "off"
  action:
    - action: switch.turn_on
      entity_id: switch.coladuria_cargador_ev
