# Turn on comfort mode when comfort state is true and is after 16:00
- id: 'Comfort - Sensor comfort mode on'
  alias: 'Comfort - Sensor comfort mode on'
  trigger:
    platform: state
    entity_id: binary_sensor.home_comfort_state
    to: 'on'
  condition:
    - condition: time
      after: '16:00'
  action:
    - service: telegram_bot.send_message
      data_template:
        message: > 
          Calefacci칩n encendida para estar m치s calentitos
          
          Temperatura objetivo: {{ states.sensor.entrance_hall_thermostat_target_temperature }}
          
          Temperatura media planta baja: {{states.sensor.ground_floor_temperature.state}}
          
          Temperatura media primera planta: {{states.sensor.first_floor_temperature.state}}
          
          Ocupaci칩n: {{states.group.unidad_familiar.state}}
          
          Estado calefacci칩n: {{states.climate.netatmo_general.state}}
          
          Modo ausente: {{is_state_attr('climate.netatmo_general', 'preset_mode', 'away')}}
          
          Estado termostato: {{states.climate.netatmo_general.attributes.hvac_mode}}
          
          Tendencia temperatura planta baja: {{states.sensor.ground_floor_temperature_trend.state}}
          
          Tendencia temperatura primera planta: {{states.sensor.first_floor_temperature_trend.state}}

        inline_keyboard: 
          - 'Desconectar:/homeassistant.turn_off#input_boolean.home_comfort_mode'

    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.home_comfort_mode
