- id: 'energy_tariff_change'
  alias: 'Energy - Tariff - Change'
  trigger:
    platform: mqtt
    topic: 'home/sensor/energy/tariff'
  action:
    - service: utility_meter.select_tariff
      data_template:
        entity_id: utility_meter.energy_grid_today
        tariff: '{{trigger.payload}}'
