##############################
# Valle tariff
# Starting at 00 and non workdays 
##############################
- alias: 'Energy - Tariff - Valle start'
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: state
      entity_id: 'binary_sensor.energy_valle_full_day_tariff'
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: 'home/sensor/energy/tariff_new'
        retain: true
        qos: 0
        payload_template: 'Valle'