- id: "energy_tariff_calendar_event_starts"
  alias: "Energy - Tariff - Calendar event starts"
  trigger:
    - platform: calendar
      event: start
      entity_id: calendar.horarios_tarifas_electricas
  action:
    - action: mqtt.publish
      data:
        topic: "home/sensor/energy/tariff"
        retain: true
        qos: 0
        payload: "{{ trigger.calendar_event.summary.split('@')[0] }}"
    - action: mqtt.publish
      data:
        topic: "home/sensor/energy/price/buy"
        retain: true
        qos: 0
        payload: "{{ trigger.calendar_event.summary.split('@')[1].split('|')[0]|float(0) }}"
    - action: mqtt.publish
      data:
        topic: "home/sensor/energy/price/sell"
        retain: true
        qos: 0
        payload: "{{ trigger.calendar_event.summary.split('@')[1].split('|')[1]|float(0) }}"
