- id: "energy_notification_ups_battery_to_be_replaced"
  alias: "Energy - Notification - UPS battery to be replaced"
  trigger:
    platform: state
    entity_id: sensor.qnapups_status
    to: "Reemplazar batería"
  action:
    - service: notify.telegram
      data:
        message: "🔋 Batería del SAI agotada, reemplazar"
