##############################
# Punta tariff
# Starting at 7:00 every day
##############################
- id: 'Energy - Tariff - Punta start'
  alias: 'Energy - Tariff - Punta start'
  trigger:
    - platform: time
      at: '7:00:00'
  action:
    - service: mqtt.publish
      data:
        topic: 'home/sensor/energy/tariff'
        retain: true
        qos: 0
        payload_template: 'Punta'
    - service: mqtt.publish
      data:
        topic: 'home/sensor/energy/price'
        retain: true
        qos: 0
        payload_template: 0.303019
