- id: 'energy_tariff_change'
  alias: 'Energy - Tariff - Change'
  trigger:
    platform: mqtt
    topic: 'home/sensor/energy/tariff'
  action:
    - action: select.select_option
      target:
        entity_id: select.energy_grid_today
      data_template:
        option: '{{trigger.payload}}'
