- id: 'Energy - Notification - UPS battery to be replaced'
  alias: 'Energy - Notification - UPS battery to be replaced'
  trigger:
    platform: state
    entity_id: sensor.energy_ups_status
    to: 'Reemplazar batería'
  action:
    - service: notify.telegram
      data:
        message: '🔋 Batería del SAI agotada, reemplazar'
    - service: notify.slack
      data_template:
        message: ''
        data:
          blocks:
            - type: 'divider'
            - type: 'section'
              text:
                type: 'mrkdwn'
                text: ':battery-low: Batería del SAI agotada, reemplazar'
            - type: 'divider'
