- id: 'energy_notification_possible_differential_switch_down'
  alias: 'Energy - Notification - Possible differential switch down'
  trigger:
    platform: state
    entity_id: switch.cargador_ev_switch, switch.luz_piscina, switch.motor_piscina, switch.piscina
    to: 'unavailable'
  condition:
    - condition: state
      entity_id: 'binary_sensor.energy_home_status'
      state: 'on'
    - condition: state
      entity_id: 'switch.cargador_ev_switch'
      state: 'unavailable'
    - condition: state
      entity_id: 'switch.luz_piscina'
      state: 'unavailable'
    - condition: state
      entity_id: 'switch.motor_piscina'
      state: 'unavailable'
    - condition: state
      entity_id: 'switch.piscina'
      state: 'unavailable'
  action:
    - service: notify.telegram
      data:
        message: 'Es posible que haya saltado un diferencial. Los dispositivos afectados son: lavavajillas, piscina (luz y depuradora), lavadora, secadora, caldera, barrera, cargador del coche, aire acondicionado, cámara de la caseta, cámara de la piscina y cámara de la barbacoa.'
