##############################
# Valle tariff
# Starting at 1AM every day
##############################
- id: 'Energy - Tariff - Valle start'
  alias: 'Energy - Tariff - Valle start'
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    - service: mqtt.publish
      data:
        topic: 'home/sensor/energy/tariff'
        retain: true
        qos: 0
        payload_template: 'Valle'
    - service: mqtt.publish
      data:
        topic: 'home/sensor/energy/price/buy'
        retain: true
        qos: 0
        payload_template: 0.038983
