- id: "misc_aeat_rss_notification"
  alias: "Misc - AEAT - RSS Notification"
  trigger:
    platform: event
    event_type: feedreader
    event_data:
      feed_url: "http://www.agenciatributaria.es/AEAT.desarrolladores/Desarrolladores/Novedades/Novedades.xml"
  condition:
    condition: or
    conditions:
      - '{{ "modelo 303" in trigger.event.data.title }}'
      - '{{ "Modelo 303" in trigger.event.data.title }}'
      - '{{ "IVA 303" in trigger.event.data.title }}'
      - '{{ "informativas" in trigger.event.data.title }}'
  action:
    # - action: input_text.set_value
    #   target:
    #     entity_id: input_text.tablon_anuncios_agencia_tributaria_title
    #   data:
    #     value: "{{ trigger.event.data.title }}"
    # - action: input_text.set_value
    #   target:
    #     entity_id: input_text.tablon_anuncios_agencia_tributaria_link
    #   data:
    #     value: "{{ trigger.event.data.link }}"
    # - action: input_text.set_value
    #   target:
    #     entity_id: input_text.tablon_anuncios_agencia_tributaria_description
    #   data:
    #     value: "{{ trigger.event.data.description }}"
    # - action: input_datetime.set_datetime
    #   data:
    #     datetime: "{{ trigger.event.data.date }}"
    #   target:
    #     entity_id: input_datetime.tablon_anuncios_agencia_tributaria_datetime
    - action: notify.send_message
      data:
        entity_id: notify.telegram_hokusphone
        message: >
          <b>Nuevo anuncio Modelo 303</b>

          <a href="{{ trigger.event.data.link }}">{{ trigger.event.data.title }}</a>

