- id: "misc_aeat_rss_notification"
  alias: "Misc - AEAT - RSS Notification"
  trigger:
    platform: event
    event_type: feedreader
    event_data:
      feed_url: "https://www.agenciatributaria.es/AEAT.desarrolladores/Desarrolladores/Novedades/Novedades.xml"
  condition:
    condition: or
    conditions:
      - '{{ "modelo 303" in trigger.event.data.title }}'
      - '{{ "Modelo 303" in trigger.event.data.title }}'
      - '{{ "IVA 303" in trigger.event.data.title }}'
      - '{{ "informativas" in trigger.event.data.title }}'
  action:
    - service: notify.telegram_hokusphone
      data:
        message: >
          <b>Anuncio Modelo 303</b>

          <a href="{{ trigger.event.data.link }}">{{ trigger.event.data.title }}</a>
