- id: "misc_aeat_rss_notification"
  alias: "Misc - AEAT - RSS Notification"
  trigger:
    platform: event
    event_type: feedreader
  condition:
    condition: or
    conditions:
      - '{{ "modelo 303" in trigger.event.data.title }}'
      - '{{ "Modelo 303" in trigger.event.data.title }}'
      - '{{ "IVA 303" in trigger.event.data.title }}'
      - '{{ "informativas" in trigger.event.data.title }}'
  action:
    - service: telegram_bot.send_message
      data_template:
        title: "<b>Agencia Tributaria - Tablón de anuncios - Desarrolladores - Anuncio Modelo 303</b>"
        message: '<a href="{{trigger.event.data.link}}">{{trigger.event.data.title}}</a>'
