- id: "person_button_coque_press_barrera"
  alias: "Person - Button - Coque press barrera"
  trigger:
    - platform: state
      entity_id: input_button.barrera_coque
  condition:
    - condition: state
      entity_id: person.coque
      state: "home"
  action:
    - service: cover.open_cover
      entity_id: cover.outside_fence
