- id: "person_button_carlos_press_barrera"
  alias: "Person - Button - Carlos press barrera"
  trigger:
    - platform: state
      entity_id: input_button.barrera_carlos
  condition:
    - condition: state
      entity_id: person.carlos
      state: "home"
  action:
    - service: cover.open_cover
      entity_id: cover.outside_fence
    - service: notify.telegram_hokusphone
      data:
        message: "Carlos ha pulsado el botón Barrera"
