- id: "person_zone_children_enter_leave_zone"
  alias: "Person - Zone - Children enter or leave zone"
  trigger:
    # Casa Abu
    - platform: zone
      zone: zone.casa_abu
      event: enter
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque
    - platform: zone
      zone: zone.casa_abu
      event: leave
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque

    # Casa Avi y Senyoravi
    - platform: zone
      zone: zone.casa_avi_y_senyoravi
      event: enter
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque
    - platform: zone
      zone: zone.casa_avi_y_senyoravi
      event: leave
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque

    # Cerca de Casa
    - platform: zone
      zone: zone.casa_cerca
      event: enter
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque
    - platform: zone
      zone: zone.casa_cerca
      event: leave
      enabled: false
      entity_id:
        - person.carlos
        - person.coque

    # Colegio
    - platform: zone
      zone: zone.colegio
      event: enter
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque
    - platform: zone
      zone: zone.colegio
      event: leave
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque

    # Casa
    - platform: zone
      zone: zone.home
      event: enter
      enabled: false
      entity_id:
        - person.carlos
        - person.coque
    - platform: zone
      zone: zone.home
      event: leave
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque

    # Sant Ferran
    - platform: zone
      zone: zone.sant_ferran
      event: enter
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque
    - platform: zone
      zone: zone.sant_ferran
      event: leave
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque

    # Son Moix
    - platform: zone
      zone: zone.son_moix
      event: enter
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque
    - platform: zone
      zone: zone.son_moix
      event: leave
      # enabled: false
      entity_id:
        - person.carlos
        - person.coque
  action:
    - variables:
        person: "{{ trigger.to_state.attributes.friendly_name }}"
        event: "{{ 'ha salido de' if trigger.event == 'leave' else 'ha llegado a' }}"
        zone: "{{ trigger.zone.attributes.friendly_name }}"

    - action: notify.telegram_familygroup
      data:
        message: "{{person}} {{event}} {{zone}}"
