- id: "person_zone_jordi_enters_home"
  alias: "Person - Zone - Jordi enters home"
  trigger:
    - platform: zone
      entity_id: person.jordi
      zone: zone.home
      event: enter
  condition:
    condition: and
    conditions:
      # Fence is closed
      - condition: state
        entity_id: cover.outside_fence
        state: "closed"
      # Car engine is on
      - condition: state
        entity_id: sensor.car_ioniq_state_sensor
        state: "Encendido"
      # Hokusphone is plugged into the one car (usually my car)
      - condition: state
        entity_id: binary_sensor.hokusphone_android_auto
        state: "on"
  action:
    - service: cover.open_cover
      entity_id: cover.outside_fence
    - service: mqtt.publish
      data:
        payload_template: >-
          He abierto la barrera. {%- if is_state("person.geni", "home") -%}Jeni está en casa.{%- else -%}Jeni no está en casa.{%- endif -%}
        retain: false
        topic: "phone/sensor/hokus/cmnd/say"
    - delay:
        seconds: 5
    - service: notify.telegram_hokusphone
      data:
        message: "🚪 Barrera abierta automáticamente"
        inline_keyboard:
          - "Cerrar:/switch.turn_on#switch.barrera"
