- id: "person_zone_jordi_enters_cargador_ev"
  alias: "Person - Zone - Jordi enters Cargador EV"
  trigger:
    - platform: zone
      entity_id: device_tracker.car_ioniq
      zone: zone.cargador_aragon
      event: enter
    - platform: zone
      entity_id: device_tracker.car_ioniq
      zone: zone.cargador_conquistador
      event: enter
    - platform: zone
      entity_id: device_tracker.car_ioniq
      zone: zone.cargador_paseo_mallorca
      event: enter
    - platform: zone
      entity_id: device_tracker.car_ioniq
      zone: zone.cargador_sant_miquel
      event: enter
    - platform: zone
      entity_id: device_tracker.car_ioniq
      zone: zone.cargador_sestanyol
      event: enter
  condition:
    condition: and
    conditions:
      # hokusphone is in car IONIQ (see binary_sensor.hokusphone_in_car_ioniq in phones.yaml)
      - condition: state
        entity_id: binary_sensor.hokusphone_in_car_ioniq
        state: "on"
  action:
    - action: mqtt.publish
      data:
        payload: >
          El {{ state_attr(trigger.zone.entity_id, "friendly_name") }} está {{ states(trigger.zone.entity_id | replace("zone", "sensor")) }}
        retain: false
        topic: "phone/sensor/hokus/cmnd/say"
