- id: "person_zone_jordi_enters_cargador_ev"
  alias: "Person - Zone - Jordi enters Cargador EV"
  trigger:
    - platform: zone
      entity_id: person.jordi
      zone: zone.cargador_aragon
      event: enter
    - platform: zone
      entity_id: person.jordi
      zone: zone.cargador_conquistador
      event: enter
    - platform: zone
      entity_id: person.jordi
      zone: zone.cargador_paseo_mallorca
      event: enter
    - platform: zone
      entity_id: person.jordi
      zone: zone.cargador_sant_miquel
      event: enter
    - platform: zone
      entity_id: person.jordi
      zone: zone.cargador_sestanyol
      event: enter
  condition:
    condition: and
    conditions:
      # Car engine is on
      - condition: state
        entity_id: sensor.car_ioniq_state_sensor
        state: "Encendido"
      # Hokusphone is plugged into the one car (usually my car)
      - condition: state
        entity_id: binary_sensor.hokusphone_android_auto
        state: "on"
  action:
    - service: mqtt.publish
      data:
        payload_template: >
          El {{ state_attr(trigger.zone.entity_id, "friendly_name") }} está {{ states(trigger.zone.entity_id | replace("zone", "sensor")) }}
        retain: false
        topic: "phone/sensor/hokus/cmnd/say"
