- id: "person_zone_jordi_enters_home"
  alias: "Person - Zone - Jordi enters home"
  trigger:
    - platform: zone
      entity_id: person.jordi
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: device_tracker.car_ioniq
      zone: zone.home
      event: enter
  condition:
    condition: and
    conditions:
      # Fence is closed
      - condition: state
        entity_id: cover.outside_fence
        state: "closed"
      # hokusphone is in car IONIQ (see binary_sensor.hokusphone_in_car_ioniq in phones.yaml)
      - condition: state
        entity_id: binary_sensor.hokusphone_in_car_ioniq
        state: "on"
  action:
    - service: cover.open_cover
      entity_id: cover.outside_fence
    - service: mqtt.publish
      data:
        payload_template: >-
          He abierto la barrera.
          {%- if distance('person.jordi', 'person.geni') * 1000 > 50 -%}
            {%- if is_state("person.geni", "home") -%}
              Jeni está en casa.
            {%- else -%}
              Jeni no está en casa.
            {%- endif -%}
          {%- endif -%}
        retain: false
        topic: "phone/sensor/hokus/cmnd/say"
    - delay:
        seconds: 5
    - service: notify.telegram_hokusphone
      data:
        message: "🚪 Barrera abierta automáticamente"
        data:
          inline_keyboard:
            - "Cerrar:/switch.turn_on#switch.barrera"
