- id: "person_zone_jordi_enters_cargador_palmanyola_dalias"
  alias: "Person - Zone - Jordi enters Cargador Palmanyola Dalias"
  trigger:
    - platform: zone
      entity_id: device_tracker.car_ioniq
      zone: zone.cargador_palmanyola_dalias
      event: enter
  condition:
    condition: and
    conditions:
      # hokusphone is in car IONIQ (see binary_sensor.hokusphone_in_car_ioniq in phones.yaml)
      - condition: state
        entity_id: binary_sensor.hokusphone_in_car_ioniq
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.cargador_palmanyola_dalias
            state: "No gestionado"
          - condition: state
            entity_id: sensor.cargador_palmanyola_dalias
            state: "Desconocido"
      - condition: numeric_state
        entity_id: sensor.car_ioniq_battery
        below: 50
  action:
    - action: mqtt.publish
      data:
        payload: >
          El {{ state_attr(trigger.zone.entity_id, "friendly_name") }} está {{ states(trigger.zone.entity_id | replace("zone", "sensor")) }}
        retain: false
        topic: "phone/sensor/hokus/cmnd/say"
