- id: 'presence_guest_calendar_event_ends'
  alias: 'Presence - Guest - Calendar event ends'
  trigger:
    - platform: calendar
      event: end
      entity_id: calendar.invitado
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.guest_mode
    - service: input_number.set_value
      target:
        entity_id: input_number.guest_mode_minutes
      data:
        value: 180
