- id: "presence_notification_new_device"
  alias: "Presence - Notification - New device"
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - action: notify.telegram_hokusphone
      data:
        title: Nuevo dispositivo conectado
        message: "Nuevo dispositivo detectado: {{trigger.event.data.host_name}} - ({{trigger.event.data.entity_id}})"
