- id: "presence_nobody_at_home_security_check"
  alias: "Presence - Nobody at home - Security check"
  trigger:
    - platform: state
      entity_id: group.todos
      from: "home"
      to: "not_home"
  conditions: "{{ label_entities('comprobacion_seguridad') | expand | selectattr('state', 'eq', 'on') | list | count > 0 }}"
  action:
    - variables:
        checkResult: >-
          {% for entity in label_entities('comprobacion_seguridad') | expand | selectattr('state', 'eq', 'on') | list %}
            La {{entity.attributes.friendly_name}} está {{state_translated(entity.entity_id) | replace("Abierto", "abierta")}}.
          {%- endfor %}
    - action: notify.send_message
      data:
        entity_id: notify.telegram_hokusphone
        message: "{{checkResult}}"
    - alias: "If in the car"
      choose:
        - conditions:
            - condition: state
              entity_id: "binary_sensor.hokusphone_in_car_ioniq"
              state: "on"
          sequence:
            - action: mqtt.publish
              data:
                payload: "{{checkResult}}"
                retain: false
                topic: "phone/sensor/hokus/cmnd/say"
    - alias: "If outside fence is open"
      choose:
        - conditions:
            - condition: state
              entity_id: "cover.outside_fence"
              state: "open"
          sequence:
            - action: cover.close_cover
              data:
                entity_id: cover.outside_fence
