- id: "presence_housekeeper_calendar_event_starts"
  alias: "Presence - Housekeeper - Calendar event starts"
  trigger:
    - platform: calendar
      event: start
      entity_id: calendar.asistente_hogar
  action:
    - service: device_tracker.see
      data:
        dev_id: asistente_hogar
        location_name: home
