- id: 'presence_guest_calendar_event_starts'
  alias: 'Presence - Guest - Calendar event starts'
  trigger:
    - platform: calendar
      event: start
      entity_id: calendar.invitado
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.guest_mode