- id: "presence_nobody_at_home_security_check"
  alias: "Presence - Nobody at home - Security check"
  trigger:
    - platform: state
      entity_id: group.todos
      from: "home"
      to: "not_home"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: cover.outside_fence
        state: "open"
      - condition: state
        entity_id: binary_sensor.entrada_sensor_puerta
        state: "on"
      - condition: state
        entity_id: binary_sensor.porche_sensor_puerta
        state: "on"
      - condition: state
        entity_id: binary_sensor.porche_sensor_persiana
        state: "on"
      - condition: state
        entity_id: binary_sensor.suite_sensor_ventana
        state: "on"
      - condition: state
        entity_id: binary_sensor.banyo_suite_sensor_ventana
        state: "on"
      - condition: state
        entity_id: binary_sensor.habitacion_coque_sensor_ventana
        state: "on"
      - condition: state
        entity_id: binary_sensor.habitacion_carlos_sensor_ventana
        state: "on"

  action:
    - variables:
        checkResult: >-
          No hay nadie en casa y 
          {% if is_state("cover.outside_fence", "open") -%}
            Se ha quedado la barrera abierta, la cierro.
          {%- endif -%}
          {% if is_state("binary_sensor.entrada_sensor_puerta", "on") %}
            La puerta de entrada está abierta.
          {%- endif -%}
          {% if is_state("binary_sensor.suite_sensor_ventana", "on") %}
            La ventana de la suite está abierta.
          {%- endif -%}
          {% if is_state("binary_sensor.habitacion_coque_sensor_ventana", "on") %}
            La ventana de la habitación de Coque está abierta.
          {%- endif -%}
          {% if is_state("binary_sensor.habitacion_carlos_sensor_ventana", "on") %}
            La ventana de la habitación de Carlos está abierta.
          {%- endif -%}
          {% if is_state("binary_sensor.banyo_suite_sensor_ventana", "on") %}
            La ventana del baño de la suite está abierta.
          {%- endif %}
          {% if is_state("binary_sensor.porche_sensor_puerta", "on") %}
            La puerta de la cocina está abierta.
          {%- endif -%}
          {% if is_state("binary_sensor.porche_sensor_persiana", "on") %}
            La persiana de la cocina está abierta.
          {%- endif -%}

    - action: notify.telegram_hokusphone
      data:
        message: "{{checkResult}}"
    - alias: "If in the car"
      choose:
        - conditions:
            - condition: state
              entity_id: "binary_sensor.hokusphone_in_car_ioniq"
              state: "on"
          sequence:
            - action: mqtt.publish
              data:
                payload: "{{checkResult}}"
                retain: false
                topic: "phone/sensor/hokus/cmnd/say"
    - alias: "If outside fence is open"
      choose:
        - conditions:
            - condition: state
              entity_id: "cover.outside_fence"
              state: "open"
          sequence:
            - action: cover.close_cover
              data:
                entity_id: cover.outside_fence
