# Consider_home is not working properly for mqtt device_tracker
# This sensor is to workaround it using some automations
# Presence - HokusPhone - Wifi home.yaml
# Presence - HokusPhone - Wifi not_home.yaml
- id: 'Presence - HokusPhone - Wifi home'
  alias: 'Presence - HokusPhone - Wifi home'
  trigger:
    - platform: state
      entity_id: sensor.hokusphone_wifi_ssid
      to: 'HokusWiFi'
  condition:
    condition: state
    entity_id: device_tracker.hokusphone_wifi
    state: 'not_home'
  action:
    - service: mqtt.publish
      data:
        topic: 'phone/sensor/hokus/wifi' 
        payload: 'home'
        qos: 0
        retain: true