- id: sistema_sai_notificar_bateria_reemplazar
  alias: "Sistema - SAI - Notificar reemplazo de batería"
  trigger:
    platform: state
    entity_id: sensor.hueco_escalera_sai_estado
    to: "Reemplazar batería"
  action:
    - action: notify.send_message
      data:
        entity_id: notify.telegram_hokusphone
        message: "🔋 Batería del SAI agotada, reemplazar"
