# Turn on swimming pool when exporting energy to the grid over a threshold (during a period of time) and it has been on less that the time expected
# and specific appliances (dish washer, tuble dryer, wasing machine,...) are off
- id: 'swimming_pool_pump_on'
  alias: 'Swimming Pool - Pump - On'
  trigger:
    # Trigger every 5 minutes
    - platform: time_pattern
      minutes: "/5"
  condition:
    condition: and
    conditions:
      # Has filtering time left
      - condition: numeric_state
        entity_id: sensor.piscina_on_history
        below: sensor.piscina_filtering_time
      # Specific appliances are off
      - condition: state
        entity_id: 
          - switch.motor_piscina
          - binary_sensor.lavadora_status
          - binary_sensor.secadora_status
          - binary_sensor.lavaplatos_status
        state: "off"
      - condition: or
        conditions:
          # There is enough energy generated to start pump OR it's in 'Valle' tariff
          - condition: state
            entity_id: binary_sensor.piscina_pump_on_energy_and_delay_met
            state: "on"
          - condition: state
            entity_id: sensor.energy_tariff
            state: "Valle"
  action:
    - service: switch.turn_on
      entity_id: switch.motor_piscina
