- id: 'Swimming Pool - Pump - Off'
  alias: 'Swimming Pool - Pump - Off'
  trigger:
    - platform: state
      entity_id: sensor.energy_tariff
      from: 'Valle'
    - platform: numeric_state
      entity_id: sensor.fronius_solarnet_power_grid
      above: input_number.piscina_pump_off_threshold
      for:
        minutes: 10
    - platform: numeric_state
      entity_id: sensor.piscina_on_history
      above: sensor.piscina_filtering_time
  action:
    - service: switch.turn_off
      entity_id: switch.motor_piscina