# Turn on swimming pool when exporting energy to the grid over a threshold (during a period of time) and it has been on less that the time expected
# and specific appliances (dish washer, tuble dryer, wasing machine,...) are off
- id: 'swimming_pool_pump_on'
  alias: 'Swimming Pool - Pump On'
  trigger:
    # Trigger every 5 minutes
    - platform: time_pattern
      minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 
          # Has filtering time left
          - binary_sensor.piscina_pump_off_filtering_time_met
          # It's not already on
          - switch.motor_piscina
          # Specific appliances are off
          - binary_sensor.lavadora_status_high_power
          - binary_sensor.secadora_status
          - binary_sensor.lavaplatos_status
        state: "off"
      # Energy net balance is negative
      - condition: numeric_state
        entity_id: sensor.energy_net_balance_hour
        below: 0
      # There is enough energy generated to start pump
#      - condition: state
#        entity_id: binary_sensor.piscina_pump_on_energy_and_delay_met
#        state: "on"
      - condition: or
        conditions:
          # There is enough energy generated to start pump OR it's in 'Valle' tariff
          - condition: state
            entity_id: binary_sensor.piscina_pump_on_energy_and_delay_met
            state: "on"
          - condition: state
            entity_id: sensor.energy_tariff
            state: "Valle"
  action:
    - service: switch.turn_on
      entity_id: switch.motor_piscina
