- id: 'swimming_pool_pump_off_filtering_time'
  alias: 'Swimming Pool - Pump Off - Filtering Time'
  trigger:
    # Trigger every 5 minutes
    - platform: time_pattern
      minutes: "/5"
  # When it has been on for calculated filtering time and not in manual mode
  condition: "{{ states('binary_sensor.piscina_pump_off_filtering_time_met') == 'on' and states('input_boolean.piscina_pump_manual_mode') == 'off' }}"
  action:
    - service: switch.turn_off
      entity_id: switch.motor_piscina