- id: 'Swimming Pool - Pump - On'
  alias: 'Swimming Pool - Pump - On'
  trigger:
    - platform: numeric_state
      entity_id: sensor.estimated_power_production_now
      above: input_number.piscina_pump_on_threshold
  action:
    - service: switch.turn_on
      entity_id: switch.motor_piscina
