- id: "swimming_pool_pump_on"
  alias: "Swimming Pool - Pump On"
  trigger:
    # When generating enough energy
    - platform: state
      entity_id: binary_sensor.piscina_pump_on_energy_export_over_threshold
      to: "on"
    # When hourly net balance is enough to turn on the pump
    - platform: state
      entity_id: binary_sensor.piscina_pump_on_enough_net_balance_hour
      to: "on"
  # Execute automation when:
  #  - 'Solar' OR 'Solar + Valle' modes
  #  - Generating enough enery OR hourly net balance is enough
  #  - Still has remaining filtering time
  #  - Pump is off
  condition:
    condition: and
    conditions:
      - alias: "'Solar' or 'Solar + Valle' modes"
        condition: or
        conditions:
          - alias: "Solar mode"
            condition: state
            entity_id: input_select.piscina_pump_mode
            state: "Solar"
          - alias: "Solar + Valle mode"
            condition: state
            entity_id: input_select.piscina_pump_mode
            state: "Solar + Valle"
      - alias: "Generating enough enery or hourly net balance is enough"
        condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.piscina_pump_on_energy_export_over_threshold
            state: "on"
          - condition: state
            entity_id: binary_sensor.piscina_pump_on_enough_net_balance_hour
            state: "on"
      - alias: "Still has remaining filtering time"
        condition: state
        entity_id: binary_sensor.piscina_pump_remaining_time
        state: "on"
      - alias: "Pump is off"
        condition: state
        entity_id: switch.motor_piscina
        state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.motor_piscina
