- id: 'System - At 5 mins past midnight'
  alias: 'System - At 5 mins past midnight'
  trigger:
    platform: time
    at: '00:05:00'
  action:
    - service: shell_command.mkv_cleanup
      data_template:
        # Age of files in days
        age: 2
    - service: shell_command.mp4_cleanup
      data_template:
        age: 2
    - service: shell_command.jpg_cleanup
      data_template:
        age: 2
    - service: shell_command.empty_directories_cleanup