- id: "system_node_red_watchdog"
  alias: "System - Node RED Watchdog"
  trigger:
    platform: state
    entity_id: sensor.node_red
    to: "unavailable"
  action:
    - action: hassio.addon_restart
      data:
        addon: a0d7b954_nodered
    - action: notify.telegram_hokusphone
      data:
        message: "He reiniciado node RED porque no repondía"
