- id: "system_notify_home_assistant_core_update"
  alias: "System - Notify Home-Assistant Core Update"
  trigger:
    platform: state
    entity_id:
      - update.home_assistant_core_update
      - update.home_assistant_supervisor_update
      - update.home_assistant_operating_system_update
    to: "on"
  action:
    - service: notify.telegram_hokusphone
      data:
        message: >
          Actualización de <b>{{ state_attr(trigger.entity_id, "title") }}</b>:

          Version instalada: <b>{{ state_attr(trigger.entity_id, "installed_version") }}</b>

          Última versión: <b>{{ state_attr(trigger.entity_id, "latest_version") }}</b>
