- id: 'System - Node RED Watchdog'
  alias: 'System - Node RED Watchdog'
  trigger:
    platform: state
    entity_id: sensor.node_red
    to: 'unavailable'
  action:
    - service: hassio.addon_restart
      data:
        addon: a0d7b954_nodered
    - service: notify.telegram
      data:
        message: 'He reiniciado node RED porque no repondía'
