- id: "webhook_ifttt_received"
  alias: "Webhook - IFTTT - Received"
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    action: "{{ trigger.event.data.service }}"
    data:
      entity_id: "{{ trigger.event.data.entity_id }}"
