ha_latitude: 0.0000
ha_longitude: 0.0000

office_latitude: 0.0000
office_longitude: 0.0000

office2_latitude: 0.0000
office2_longitude: 0.0000

school_latitude: 0.0000
school_longitude: 0.0000

ha_base_url: https://redacted.com
ha_api_password: redacted

recorder_db_url: mysql://redacted

telegram_api_key: redacted
hokusphone_telegram_chat_id: 0
hokuscar_telegram_chat_id: 0
geniphone_telegram_chat_id: 0
familygroup_telegram_chat_id: 0

google_api_key: redacted
camera_ioniq_still_image_url: redacted

google_client_id: redacted
google_secret: redacted

ifttt_api_key: redacted

netatmo_client_id: redacted
netatmo_secret_key: redacted

withings_client_id: redacted
withings_client_secret: redacted

dark_sky_api_key: redacted

efergy_app_token: redacted

cam_recibidor_host: 0.0.0.0
cam_recibidor_port: 80
cam_recibidor_username: redacted
cam_recibidor_password: redacted
cam_recibidor_infrared_command: 'redacted'
cam_recibidor_motion_detection_on: 'redacted'
cam_recibidor_motion_detection_off: 'redacted'
cam_recibidor_motion_detection_state: 'redacted'

cam_salon_host: 0.0.0.0
cam_salon_port: 80
cam_salon_username: redacted
cam_salon_password: redacted
cam_salon_infrared_command: 'redacted'
cam_salon_motion_detection_on: 'redacted'
cam_salon_motion_detection_off: 'redacted'
cam_salon_motion_detection_state: 'redacted'
cam_salon_ptz_preset_point_main: 'redacted'
cam_salon_ptz_preset_point_mainleft: 'redacted'
cam_salon_ptz_preset_point_mainright: 'redacted'

cam_cocina_host: 0.0.0.0
cam_cocina_port: 80
cam_cocina_username: redacted
cam_cocina_password: redacted
cam_cocina_infrared_command: 'redacted'
cam_cocina_motion_detection_on: 'redacted'
cam_cocina_motion_detection_off: 'redacted'
cam_cocina_motion_detection_state: 'redacted'

cam_piscina_host: 0.0.0.0
cam_piscina_port: 80
cam_piscina_username: redacted
cam_piscina_password: redacted
cam_piscina_infrared_command: 'redacted'
cam_piscina_motion_detection_on: 'redacted'
cam_piscina_motion_detection_off: 'redacted'
cam_piscina_motion_detection_state: 'redacted'

cam_caseta_host: 0.0.0.0
cam_caseta_port: 80
cam_caseta_still_image_url: http://redacted
cam_caseta_mjpeg_url: http://redacted
cam_caseta_username: redacted
cam_caseta_password: redacted
cam_caseta_motion_detection_on: 'redacted'
cam_caseta_motion_detection_off: 'redacted'
cam_caseta_motion_detection_state: 'redacted'

cam_barbacoa_host: 0.0.0.0
cam_barbacoa_port: 80
cam_barbacoa_username: redacted
cam_barbacoa_password: redacted
cam_barbacoa_infrared_command: 'redacted'
cam_barbacoa_motion_detection_on: 'redacted'
cam_barbacoa_motion_detection_off: 'redacted'
cam_barbacoa_motion_detection_state: 'redacted'

iframe_shift_calendar_url: 'https://redacted'

hokusphone_jordi_picture: 'https://redacted'
geni_picture: '/local/hass-geni2.jpg'
guest_picture: '/local/guest.png'

cert_expiry_host: redacted

bitcoincash_balance: 0.0
bitcoin_balance: 0.0
ethereum_balance: 0.0

domain_name1: redacted
domain_name2: redacted

slack_token: redacted

lock_nuki_host: redacted
lock_nuki_token: redacted

freedns_url: http://sync.afraid.org/u/RANDOMIZED_TOKEN/
