recorder_db_url: mysql://redacted

camara_recibidor_deteccion_movimiento_activar: 'redacted'
camara_recibidor_deteccion_movimiento_desactivar: 'redacted'
camara_recibidor_deteccion_movimiento_estado: 'redacted'

camara_salon_deteccion_movimiento_activar: 'redacted'
camara_salon_deteccion_movimiento_desactivar: 'redacted'
camara_salon_deteccion_movimiento_estado: 'redacted'
camara_salon_ptz_posicion_predefinida_principal: 'redacted'
camara_salon_ptz_posicion_predefinida_principal_izquierda: 'redacted'
camara_salon_ptz_posicion_predefinida_principal_derecha: 'redacted'

camara_cocina_deteccion_movimiento_activar: 'redacted'
camara_cocina_deteccion_movimiento_desactivar: 'redacted'
camara_cocina_deteccion_movimiento_estado: 'redacted'

camara_piscina_deteccion_movimiento_activar: 'redacted'
camara_piscina_deteccion_movimiento_desactivar: 'redacted'
camara_piscina_deteccion_movimiento_estado: 'redacted'

camara_barbacoa_deteccion_movimiento_activar: 'redacted'
camara_barbacoa_deteccion_movimiento_desactivar: 'redacted'
camara_barbacoa_deteccion_movimiento_estado: 'redacted'

freedns_url: http://sync.afraid.org/u/RANDOMIZED_TOKEN/
