recorder_db_url: mysql://redacted

cam_recibidor_infrared_command: 'redacted'
cam_recibidor_motion_detection_on: 'redacted'
cam_recibidor_motion_detection_off: 'redacted'
cam_recibidor_motion_detection_state: 'redacted'

cam_salon_infrared_command: 'redacted'
cam_salon_motion_detection_on: 'redacted'
cam_salon_motion_detection_off: 'redacted'
cam_salon_motion_detection_state: 'redacted'
cam_salon_ptz_preset_point_main: 'redacted'
cam_salon_ptz_preset_point_mainleft: 'redacted'
cam_salon_ptz_preset_point_mainright: 'redacted'

cam_cocina_infrared_command: 'redacted'
cam_cocina_motion_detection_on: 'redacted'
cam_cocina_motion_detection_off: 'redacted'
cam_cocina_motion_detection_state: 'redacted'

cam_piscina_infrared_command: 'redacted'
cam_piscina_motion_detection_on: 'redacted'
cam_piscina_motion_detection_off: 'redacted'
cam_piscina_motion_detection_state: 'redacted'

cam_barbacoa_infrared_command: 'redacted'
cam_barbacoa_motion_detection_on: 'redacted'
cam_barbacoa_motion_detection_off: 'redacted'
cam_barbacoa_motion_detection_state: 'redacted'

freedns_url: http://sync.afraid.org/u/RANDOMIZED_TOKEN/