sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_2:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_3:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_4:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_2:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_3:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_4:
  ignored: true
  polling_intensity: 0
